# PA2 cpp compiler
.PHONY: all run clean
all: 110501544_PA2.cpp
	g++ -std=c++11 110501544_PA2.cpp -o exe
run:
	./exe $(input) $(output)
run0:
	./exe $(input) $(output) $(i)
clean:
	rm exe


# # PA2 cpp compiler
# .PHONY: chmod check chatgpt test2 test case0 case1 case2 all clean
# O = run
# # C = *.cpp
# P = PA2.cpp

# chmod:
# 	chmod 700 PA2_CHECKER
# check: 
# 	./PA2_CHECKER case$(c) case$(c)_output
# chatgpt:
# 	g++ -std=c++11 -o $(O) Chatgpt.cpp
# 	./$(O) case$(i) case$(i)_output_chatgpt
# test2:
# 	g++ -std=c++11 -o $(O) test2.cpp
# 	./$(O) case$(i) case$(i)_output
# test:
# 	g++ -std=c++11 -o $(O) test.cpp
# 	./$(O) case$(i) case$(i)_output
# case0:
# 	g++ -std=c++11 -o $(O) $(P)
# 	./$(O) case0 case0_output
# case1:
# 	g++ -std=c++11 -o $(O) $(P)
# 	./$(O) case1 case1_output
# case2:
# 	g++ -std=c++11 -o $(O) $(P)
# 	./$(O) case2 case2_output
# all:
# 	g++ -std=c++11 -o $(O) $(P)
# 	./$(O) case1 case1_output
# 	g++ -std=c++11 -o $(O) $(P)
# 	./$(O) case2 case2_output
# clean:
# 	rm -rf $(O)


# # PA2 cpp compiler
# .PHONY: all run clean
# all: pa2_main.o pa2_function.o
# 	g++ -std=c++11 pa2_main.o pa2_function.o -o exe
# run:
# 	./exe $(input) $(output)
# clean:
# 	rm  *.o
# pa2_main.o: pa2_main.cpp
# 	g++ -std=c++11 -c pa2_main.cpp
# pa2_function.o: pa2_function.h pa2_function.cpp
# 	g++ -std=c++11 -c pa2_function.h pa2_function.cpp

